version: '3.9'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    working_dir: /api-gateway
    links:
      - cloud-config
      - eureka-server
      - auth-service
      - order-service
      - db-order
      - db-auth


  cloud-config:
    build:
      context: ./cloud-config
      dockerfile: Dockerfile
    container_name: cloud-config
    working_dir: /cloud-config


  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    working_dir: /eureka-server
    links:
      - cloud-config




  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    links:
      - db-auth
      - cloud-config
      - eureka-server



  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service



  db-order:
    image: postgres:15-alpine
    restart: always
    container_name: db-order
    environment:
      - 'POSTGRES_USER=ipcorp'
      - 'POSTGRES_DB=ipcorp-order'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-order:/var/lib/postgresql/data



  db-auth:
    image: postgres:15-alpine
    restart: always
    container_name: db-auth
    environment:
      - 'POSTGRES_USER=ipcorp'
      - 'POSTGRES_DB=ipcorp-auth'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - db-auth:/var/lib/postgresql/data



volumes:
  db-order:
  db-auth:

