version: '3.9'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    expose:
      - "8765"
    container_name: api-gateway
    working_dir: /api-gateway
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://cloud-config:8888



  cloud-config:
    build:
      context: ./cloud-config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    expose:
      - "8888"
    container_name: cloud-config
    working_dir: /cloud-config



  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    container_name: eureka-server
    working_dir: /eureka-server
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka






  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    container_name: auth-service
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://cloud-config:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5434/ipcorp-auth
      - SPRING_DATASOURCE_USERNAME=ipcorp
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    container_name: order-service
    environment:
      - DISCOVERY_SERVICE_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://cloud-config:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-order:5432/ipcorp-order
      - SPRING_DATASOURCE_USERNAME=ipcorp
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_CONFIG_IMPORT=configserver:http://cloud-config:8888
#      - SPRING_PROFILES_ACTIVE=micro




  db-order:
    image: postgres:15-alpine
    restart: always
    container_name: db-order
    environment:
      - 'POSTGRES_USER=ipcorp'
      - 'POSTGRES_DB=ipcorp-order'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-order:/var/lib/postgresql/data




  db-auth:
    image: postgres:15-alpine
    restart: always
    container_name: db-auth
    environment:
      - 'POSTGRES_USER=ipcorp'
      - 'POSTGRES_DB=ipcorp-auth'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - db-auth:/var/lib/postgresql/data




volumes:
  db-order:
  db-auth:

